module.exports = {
  plugins: ['@typescript-eslint'],
  rules: {
    '@typescript-eslint/brace-style': 'warn',
    '@typescript-eslint/comma-spacing': 'warn',
    '@typescript-eslint/default-param-last': 'warn',
    '@typescript-eslint/dot-notation': 'warn',
    '@typescript-eslint/func-call-spacing': 'warn',
    '@typescript-eslint/indent': ['warn', 2],
    '@typescript-eslint/init-declarations': 'warn',
    '@typescript-eslint/keyword-spacing': 'warn',
    '@typescript-eslint/lines-between-class-members': 'warn',
    '@typescript-eslint/no-array-constructor': 'warn',
    '@typescript-eslint/no-dupe-class-members': 'warn',
    '@typescript-eslint/no-empty-function': 'warn',
    '@typescript-eslint/no-extra-parens': [
      'error',
      'all',
      {
        conditionalAssign: true,
        enforceForArrowConditionals: true,
        ignoreJSX: 'multi-line',
        nestedBinaryExpressions: true,
        returnAssign: true,
      },
    ],
    '@typescript-eslint/no-extra-semi': 'warn',
    '@typescript-eslint/no-invalid-this': 'warn',
    '@typescript-eslint/no-loss-of-precision': 'warn',
    '@typescript-eslint/no-magic-numbers': 'warn',
    '@typescript-eslint/no-unused-expressions': 'warn',
    '@typescript-eslint/no-unused-vars': 'error',
    '@typescript-eslint/no-use-before-define': 'warn',
    '@typescript-eslint/no-useless-constructor': 'warn',
    '@typescript-eslint/quotes': ['warn', 'single', { allowTemplateLiterals: false, avoidEscape: false }],
    '@typescript-eslint/require-await': 'error',
    '@typescript-eslint/return-await': ['error', 'never'],
    '@typescript-eslint/semi': ['error', 'always', { omitLastInOneLineBlock: false }],
    '@typescript-eslint/space-before-function-paren': [
      'warn',
      { anonymous: 'never', asyncArrow: 'always', named: 'never' },
    ],
  },
};
