module.exports = {
  plugins: ['react'],
  rules: {
    'react/jsx-boolean-value': 'warn',
    'react/jsx-child-element-spacing': 'warn',
    'react/jsx-closing-bracket-location': 'warn',
    'react/jsx-closing-tag-location': 'warn',
    'react/jsx-curly-brace-presence': 'warn',
    'react/jsx-curly-newline': 'warn',
    'react/jsx-curly-spacing': 'warn',
    'react/jsx-equals-spacing': 'warn',
    'react/jsx-filename-extension': ['error', { extensions: ['.js', '.tsx'] }],
    'react/jsx-first-prop-new-line': 'warn',
    'react/jsx-fragments': 'warn',
    'react/jsx-handler-names': 'warn',
    'react/jsx-indent': ['warn', 2, { checkAttributes: false, indentLogicalExpressions: false }],
    'react/jsx-indent-props': 'warn',
    'react/jsx-key': 'warn',
    'react/jsx-max-depth': 'off',
    'react/jsx-max-props-per-line': 'warn',
    'react/jsx-no-bind': 'warn',
    'react/jsx-no-comment-textnodes': 'warn',
    'react/jsx-no-duplicate-props': 'warn',
    'react/jsx-no-literals': 'off',
    'react/jsx-no-script-url': 'warn',
    'react/jsx-no-target-blank': 'warn',
    'react/jsx-no-undef': 'warn',
    'react/jsx-no-useless-fragment': 'warn',
    'react/jsx-one-expression-per-line': ['warn', { allow: 'literal' }],
    'react/jsx-pascal-case': 'warn',
    'react/jsx-props-no-multi-spaces': 'warn',
    'react/jsx-props-no-spreading': 'warn',
    'react/jsx-sort-default-props': 'warn',
    'react/jsx-sort-props': 'warn',
    'react/jsx-tag-spacing': 'warn',
    'react/jsx-uses-react': 'error',
    'react/jsx-uses-vars': 'error',
    'react/jsx-wrap-multilines': 'warn',
  },
};
