module.exports = {
  rules: {
    'array-bracket-newline': ['warn', { minItems: 3, multiline: true }],
    'array-bracket-spacing': ['warn', 'never', { arraysInArrays: false, objectsInArrays: false, singleValue: false }],
    'array-element-newline': ['warn', { minItems: 3, multiline: true }],
    'block-spacing': ['warn', 'always'],
    'brace-style': ['warn', '1tbs', { allowSingleLine: false }],
    'camelcase': ['warn', { allow: [], ignoreDestructuring: false, properties: 'always' }],
    'capitalized-comments': [
      'warn',
      'always',
      { ignoreConsecutiveComments: true, ignoreInlineComments: true, ignorePattern: 'pragma' },
    ],
    'comma-dangle': [
      'warn',
      {
        arrays: 'always-multiline',
        exports: 'always-multiline',
        functions: 'never',
        imports: 'always-multiline',
        objects: 'always-multiline',
      },
    ],
    'comma-spacing': ['warn', { after: true, before: false }],
    'comma-style': [
      'warn',
      'last',
      {
        exceptions: {
          ArrayExpression: false,
          ArrayPattern: false,
          ArrowFunctionExpression: false,
          CallExpression: false,
          FunctionDeclaration: false,
          FunctionExpression: false,
          ImportDeclaration: false,
          NewExpression: false,
          ObjectExpression: false,
          ObjectPattern: false,
          VariableDeclaration: false,
        },
      },
    ],
    'computed-property-spacing': ['warn', 'never'],
    'consistent-this': ['warn', 'self'],
    'eol-last': ['warn', 'always'],
    'func-call-spacing': ['warn', 'never'],
    'func-name-matching': [
      'warn',
      'always',
      { considerPropertyDescriptor: false, includeCommonJSModuleExports: false },
    ],
    'func-names': ['warn', 'as-needed', { generators: 'always' }],
    'func-style': ['warn', 'declaration', { allowArrowFunctions: true }],
    'function-paren-newline': ['warn', 'consistent'],
    'id-blacklist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    'implicit-arrow-linebreak': ['warn', 'beside'],
    'indent': ['warn', 2],
    'jsx-quotes': ['warn', 'prefer-double'],
    'key-spacing': ['warn', { mode: 'strict' }],
    'keyword-spacing': ['warn', { after: true, before: true, overrides: {} }],
    'line-comment-position': [
      'warn',
      { applyDefaultIgnorePatterns: false, ignorePattern: 'pragma', position: 'above' },
    ],
    'linebreak-style': ['warn', 'unix'],
    'lines-around-comment': 'off',
    'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: false }],
    'max-depth': ['warn', { max: 4 }],
    'max-len': [
      'warn',
      {
        code: 120,
        comments: 65,
        ignoreComments: false,
        ignorePattern: '',
        ignoreRegExpLiterals: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: false,
        ignoreTrailingComments: false,
        ignoreUrls: true,
        tabWidth: 2,
      },
    ],
    'max-lines': ['warn', { max: 300, skipBlankLines: true, skipComments: true }],
    'max-lines-per-function': ['warn', { IIFEs: true, max: 20, skipBlankLines: true, skipComments: true }],
    'max-nested-callbacks': ['warn', { max: 3 }],
    'max-params': ['warn', { max: 3 }],
    'max-statements': ['warn', { max: 10 }, { ignoreTopLevelFunctions: true }],
    'max-statements-per-line': ['warn', { max: 1 }],
    'multiline-comment-style': ['warn', 'separate-lines'],
    'multiline-ternary': 'off',
    'new-cap': [
      'warn',
      {
        capIsNew: true,
        capIsNewExceptionPattern: '',
        capIsNewExceptions: [],
        newIsCap: true,
        newIsCapExceptionPattern: '',
        newIsCapExceptions: [],
        properties: false,
      },
    ],
    'new-parens': ['warn', 'always'],
    'newline-per-chained-call': ['warn', { ignoreChainWithDepth: 2 }],
    'no-array-constructor': 'warn',
    'no-bitwise': ['warn', { allow: [], int32Hint: false }],
    'no-continue': 'warn',
    'no-inline-comments': 'warn',
    'no-lonely-if': 'warn',
    'no-mixed-operators': [
      'warn',
      {
        allowSamePrecedence: true,
        groups: [
          ['+', '-', '*', '/', '%', '**'],
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
      },
    ],
    'no-mixed-spaces-and-tabs': ['warn', 'smart-tabs'],
    'no-multi-assign': 'error',
    'no-multiple-empty-lines': ['warn', { max: 2, maxBOF: 1, maxEOF: 1 }],
    'no-negated-condition': 'warn',
    'no-nested-ternary': 'warn',
    'no-new-object': 'warn',
    'no-plusplus': ['warn', { allowForLoopAfterthoughts: true }],
    'no-restricted-syntax': ['warn', 'FunctionExpression', 'WithStatement'],
    'no-tabs': ['warn', { allowIndentationTabs: false }],
    'no-ternary': 'off',
    'no-trailing-spaces': ['warn', { ignoreComments: false, skipBlankLines: false }],
    'no-underscore-dangle': [
      'warn',
      { allow: [], allowAfterSuper: false, allowAfterThis: false, enforceInMethodNames: false },
    ],
    'no-unneeded-ternary': ['warn', { defaultAssignment: false }],
    'no-whitespace-before-property': 'warn',
    'nonblock-statement-body-position': ['warn', 'below', { overrides: {} }],
    'object-curly-newline': [
      'warn',
      {
        ExportDeclaration: { minProperties: 3, multiline: true },
        ImportDeclaration: 'never',
        ObjectExpression: { consistent: true },
        ObjectPattern: { multiline: true },
      },
    ],
    'object-curly-spacing': ['warn', 'always', { arraysInObjects: true, objectsInObjects: true }],
    'object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
    'one-var': ['warn', 'never'],
    'one-var-declaration-per-line': ['warn', 'always'],
    'operator-assignment': ['warn', 'always'],
    'operator-linebreak': ['warn', 'before', { overrides: {} }],
    'padded-blocks': [
      'warn',
      { blocks: 'never', classes: 'never', switches: 'never' },
      { allowSingleLineBlocks: false },
    ],
    'padding-line-between-statements': 'off',
    'prefer-object-spread': 'warn',
    'quote-props': ['warn', 'consistent-as-needed', { keywords: true, numbers: true, unnecessary: true }],
    'quotes': ['warn', 'single', { allowTemplateLiterals: false, avoidEscape: false }],
    'semi': ['error', 'always', { omitLastInOneLineBlock: false }],
    'semi-spacing': ['warn', { after: true, before: false }],
    'semi-style': ['warn', 'last'],
    'sort-keys': ['warn', 'asc', { caseSensitive: true, minKeys: 3, natural: true }],
    'sort-vars': ['warn', { ignoreCase: false }],
    'space-before-blocks': ['warn', { classes: 'always', functions: 'always', keywords: 'always' }],
    'space-before-function-paren': ['warn', { anonymous: 'never', asyncArrow: 'always', named: 'never' }],
    'space-in-parens': ['warn', 'never', { exceptions: [] }],
    'space-infix-ops': ['warn', { int32Hint: false }],
    'space-unary-ops': ['warn', { nonwords: false, overrides: {}, words: true }],
    'spaced-comment': ['warn', 'always', { exceptions: [], markers: [] }],
    'switch-colon-spacing': ['warn', { after: true, before: false }],
    'template-tag-spacing': ['warn', 'never'],
    'unicode-bom': ['warn', 'never'],
    'wrap-regex': 'off',
  },
};
