name: NPM token
description: Set NPM token
inputs:
  GITHUB_TOKEN:
    description: '@stillmine github package registry token'
    required: true
runs:
  using: composite
  steps:
    - run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.GITHUB_TOKEN }}\n@stillmine:registry=https://npm.pkg.github.com" | tee .npmrc
      shell: bash
