module.exports = {
  plugins: ['node'],
  rules: {
    'node/callback-return': 'warn',
    'node/exports-style': 'off',
    'node/file-extension-in-import': ['warn', 'always', { '.js': 'never', '.ts': 'never', '.tsx': 'never' }],
    'node/global-require': 'warn',
    'node/no-mixed-requires': ['warn', { grouping: false, allowCall: false }],
    'node/no-process-env': 'warn',
    'node/no-restricted-import': 'off',
    'node/no-restricted-require': 'off',
    'node/no-sync': ['warn', { allowAtRootLevel: false }],
    'node/prefer-global/buffer': ['warn', 'always'],
    'node/prefer-global/console': ['warn', 'always'],
    'node/prefer-global/process': ['warn', 'always'],
    'node/prefer-global/text-decoder': ['warn', 'always'],
    'node/prefer-global/text-encoder': ['warn', 'always'],
    'node/prefer-global/url': ['warn', 'always'],
    'node/prefer-global/url-search-params': ['warn', 'always'],
    'node/prefer-promises/dns': 'warn',
    'node/prefer-promises/fs': 'warn',
  },
};
