name: Auto Merge
on:
  pull_request:
    types:
      - opened
  check_suite:
    types:
      - completed
jobs:
  AutoMerge:
    name: Auto Merge
    runs-on: ubuntu-18.04
    steps:
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
