name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  prepare-cache:
    name: Prepare cache
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
  package-artifact:
    name: Upload package artifact
    needs: prepare-cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm run build --if-present --recursive
      - uses: actions/upload-artifact@v2
        with:
          name: stillmine-artifact
          path: |
            packages/*/esm/**/*
            packages/*/lib/**/*
  typecheck:
    name: Run typecheck
    needs: package-artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@v2
        with:
          name: stillmine-artifact
          path: packages
      - run: pnpm run typecheck --if-present --recursive
  lint:
    name: Run lint
    needs: package-artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@v2
        with:
          name: stillmine-artifact
          path: packages
      - run: pnpm run lint --if-present --recursive
  test:
    name: Run test
    needs: package-artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@v2
        with:
          name: stillmine-artifact
          path: packages
      - run: pnpm test --if-present --recursive
