name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  CI:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn --immutable --immutable-cache
      - name: Run Typecheck
        run: yarn changed foreach --git-range=origin/main -p run typecheck
      - name: Run Lint
        run: yarn changed foreach --git-range=origin/main -p run lint
      - name: Run Test
        run: yarn changed foreach --git-range=origin/main -p run test
