name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  prepare-cache:
    name: Prepare cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@stillmine'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  package-artifact:
    name: Upload package artifact
    needs: prepare-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@stillmine'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build --workspaces
      - uses: actions/upload-artifact@v2
        with:
          name: stillmine-artifact
          path: |
            packages/*/esm/**/*
            packages/*/lib/**/*
  typecheck:
    name: Run typecheck
    needs: package-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@stillmine'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: stillmine-artifact
          path: packages
      - run: npm run typecheck
  lint:
    name: Run lint
    needs: package-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@stillmine'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: stillmine-artifact
          path: packages
      - run: npm run lint
  test:
    name: Run test
    needs: package-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@stillmine'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: stillmine-artifact
          path: packages
      - run: npm run test
