name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  CI:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn --immutable --immutable-cache
      - name: Run Typecheck
        run: yarn workspaces since run typecheck origin/main
      - name: Run Lint
        run: yarn workspaces since run lint origin/main
      - name: Run Test
        run: yarn workspaces since run test origin/main
