name: Release
on:
  push:
    branches:
      - main
      - next
      - ci/**
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14
          registry-url: https://npm.pkg.github.com
          scope: '@stillmine'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install -g pnpm
      - run: pnpm install
      - uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
