name: Release
on:
  push:
    branches:
      - main
      - next
      - ci/lerna
permissions:
  packages: read|write
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    env:
      HUSKY: 0
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/npm
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --immutable --immutable-cache
      - run: yarn publish
