name: Release
on:
  push:
    branches:
      - main
      - next
      - ci/lerna
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    env:
      HUSKY: 0
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14
          registry-url: https://npm.pkg.github.com
          scope: '@stillmine'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat $NPM_CONFIG_USERCONFIG
      - run: yarn --immutable --immutable-cache
      - run: yarn publish --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
